swagger: "2.0"
info:
  title: NamedEntityRecognition
  version: version not set
tags:
  - name: NamedEntityRecognition
    description: "The MessageBird Named Entity Recognition API extracts and parses a fixed set of entities from incoming phrases. A phrase is usually the text from an incoming message of your customer. This can happen in the context of receiving a Conversations API message or when receiving an SMS message, just to name a few. \n\nAn entity contains structured information, such as person names, time, durations, locations etc. The process of finding and parsing entities from phrases is known as named entity recognition. \n\nGoing from an unstructured phrase to structured data can be helpful for building intelligent conversational systems, such as chatbots. Chatbots often need to repeat information that was already said, for example to confirm whether they have extracted the right information. In other cases you might want your chat bot to call an internal or external API with a structured object. These things become straightforward using the MessageBird Named Entity Recognition API."
host: ner.messagebird.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/predict-entities:
    post:
      summary: Extract named entities from a phrase
      description: "Extracts named entities from a phrase. If no entities can be found, it returns an empty collection of entities. Each entity contains one or more (ambiguous) interpretations. Each recognized entity will most likely contain only one possible interpretation. \n\nYou can limit the named entities to search for by explicitly providing the entity types. If no types are specified upfront, all entity types will be extracted and returned if possible. \n\nIf no language is specified upfront, the Named Entity Recognition API will try to infer it automatically before proceeding with named entity recognition. An inferred or pre-specified language that is not supported will yield an error."
      operationId: NamedEntityRecognition_PredictEntities
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1PredictEntitiesResponse'
        "401":
          description: Returned when the user is not authorized.
          schema: {}
        "404":
          description: Returned when the resource does not exist.
          schema: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1PredictEntitiesRequest'
      tags:
        - NamedEntityRecognition
      security:
        - AccessKey: []
  /api/v1/supported-languages:
    get:
      summary: Get supported languages.
      description: Lists the supported entity types per language.
      operationId: NamedEntityRecognition_ListSupportedLanguages
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListSupportedLanguagesResponses'
        "401":
          description: Returned when the user is not authorized.
          schema: {}
        "404":
          description: Returned when the resource does not exist.
          schema: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - NamedEntityRecognition
      security:
        - AccessKey: []
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
  v1AmountOfMoneyValue:
    type: object
    example:
      cents: 3
      currencyCode:
        value: EUR
      currencyName: Dollar
      units: 3
    properties:
      units:
        type: string
        format: uint64
        example: 3
        description: The whole units of money. If the entity is `$3.05`, then `units` is `3`.
        title: Units
      cents:
        type: integer
        format: int64
        example: 3
        description: The number of cents. If the entity is `$3.05`, then `cents` is `5`.
        title: Cents
      currencyCode:
        $ref: '#/definitions/v1CurrencyCodeIso4217Value'
        example:
          value: EUR
        description: Wrapper with the [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) (if known).
        title: Currency Code
      currencyName:
        type: string
        example: Dollar
        description: The name of the currency. Some currency names are not ISO4217 compliant. For those cases, this will hold the currency as a string. These include `"Cent"`, `"Dinar"`, `"Dollar"`, `"Rial"`, `"Riyal"`, `"Pound"`, `"PTS"`.
        title: Currency Name
    description: An amount of money expressed in whole units, cents and a currency.
    title: AmountOfMoneyValue
  v1CurrencyCodeIso4217:
    type: string
    enum:
      - INVALID_CURRENCY_CODE
      - ADP
      - AED
      - AFA
      - AFN
      - ALK
      - ALL
      - AMD
      - ANG
      - AOA
      - AOK
      - AON
      - AOR
      - ARA
      - ARP
      - ARS
      - ARY
      - ATS
      - AUD
      - AWG
      - AYM
      - AZM
      - AZN
      - BAD
      - BAM
      - BBD
      - BDT
      - BEC
      - BEF
      - BEL
      - BGJ
      - BGK
      - BGL
      - BGN
      - BHD
      - BIF
      - BMD
      - BND
      - BOB
      - BOP
      - BOV
      - BRB
      - BRC
      - BRE
      - BRL
      - BRN
      - BRR
      - BSD
      - BTN
      - BUK
      - BWP
      - BYB
      - BYN
      - BYR
      - BZD
      - CAD
      - CDF
      - CHC
      - CHE
      - CHF
      - CHW
      - CLF
      - CLP
      - CNY
      - COP
      - COU
      - CRC
      - CSD
      - CSJ
      - CSK
      - CUC
      - CUP
      - CVE
      - CYP
      - CZK
      - DDM
      - DEM
      - DJF
      - DKK
      - DOP
      - DZD
      - ECS
      - ECV
      - EEK
      - EGP
      - ERN
      - ESA
      - ESB
      - ESP
      - ETB
      - EUR
      - FIM
      - FJD
      - FKP
      - FRF
      - GBP
      - GEK
      - GEL
      - GHC
      - GHP
      - GHS
      - GIP
      - GMD
      - GNE
      - GNF
      - GNS
      - GQE
      - GRD
      - GTQ
      - GWE
      - GWP
      - GYD
      - HKD
      - HNL
      - HRD
      - HRK
      - HTG
      - HUF
      - IDR
      - IEP
      - ILP
      - ILR
      - ILS
      - INR
      - IQD
      - IRR
      - ISJ
      - ISK
      - ITL
      - JMD
      - JOD
      - JPY
      - KES
      - KGS
      - KHR
      - KMF
      - KPW
      - KRW
      - KWD
      - KYD
      - KZT
      - LAJ
      - LAK
      - LBP
      - LKR
      - LRD
      - LSL
      - LSM
      - LTL
      - LTT
      - LUC
      - LUF
      - LUL
      - LVL
      - LVR
      - LYD
      - MAD
      - MDL
      - MGA
      - MGF
      - MKD
      - MLF
      - MMK
      - MNT
      - MOP
      - MRO
      - MTL
      - MTP
      - MUR
      - MVQ
      - MVR
      - MWK
      - MXN
      - MXP
      - MXV
      - MYR
      - MZE
      - MZM
      - MZN
      - NAD
      - NGN
      - NIC
      - NIO
      - NLG
      - NOK
      - NPR
      - NZD
      - OMR
      - PAB
      - PEH
      - PEI
      - PEN
      - PES
      - PGK
      - PHP
      - PKR
      - PLN
      - PLZ
      - PTE
      - PYG
      - QAR
      - RHD
      - ROK
      - ROL
      - RON
      - RSD
      - RUB
      - RUR
      - RWF
      - SAR
      - SBD
      - SCR
      - SDD
      - SDG
      - SDP
      - SEK
      - SGD
      - SHP
      - SIT
      - SKK
      - SLL
      - SOS
      - SRD
      - SRG
      - SSP
      - STD
      - SUR
      - SVC
      - SYP
      - SZL
      - THB
      - TJR
      - TJS
      - TMM
      - TMT
      - TND
      - TOP
      - TPE
      - TRL
      - TRY
      - TTD
      - TWD
      - TZS
      - UAH
      - UAK
      - UGS
      - UGW
      - UGX
      - USD
      - USN
      - USS
      - UYI
      - UYN
      - UYP
      - UYU
      - UZS
      - VEB
      - VEF
      - VNC
      - VND
      - VUV
      - WST
      - XAF
      - XAG
      - XAU
      - XBA
      - XBB
      - XBC
      - XBD
      - XCD
      - XDR
      - XEU
      - XFO
      - XFU
      - XOF
      - XPD
      - XPF
      - XPT
      - XRE
      - XSU
      - XTS
      - XUA
      - XXX
      - YDD
      - YER
      - YUD
      - YUM
      - YUN
      - ZAL
      - ZAR
      - ZMK
      - ZMW
      - ZRN
      - ZRZ
      - ZWC
      - ZWD
      - ZWL
      - ZWN
      - ZWR
    default: INVALID_CURRENCY_CODE
    valueComments:
      - Invalid currency code..
      - Andorran Peseta, no longer an active currency.
      - UAE Dirham.
      - Afghani, no longer an active currency.
      - Afghani.
      - Old Lek, no longer an active currency.
      - Lek.
      - Armenian Dram.
      - Netherlands Antillean Guilder.
      - Kwanza.
      - Kwanza, no longer an active currency.
      - New Kwanza, no longer an active currency.
      - Kwanza Reajustado, no longer an active currency.
      - Austral, no longer an active currency.
      - Peso Argentino, no longer an active currency.
      - Argentine Peso.
      - Peso, no longer an active currency.
      - Schilling, no longer an active currency.
      - Australian Dollar.
      - Aruban Florin.
      - Azerbaijan Manat, no longer an active currency.
      - Azerbaijanian Manat, no longer an active currency.
      - Azerbaijan Manat.
      - Dinar, no longer an active currency.
      - Convertible Mark.
      - Barbados Dollar.
      - Taka.
      - Convertible Franc, no longer an active currency.
      - Belgian Franc, no longer an active currency.
      - Financial Franc, no longer an active currency.
      - Lev A/52, no longer an active currency.
      - Lev A/62, no longer an active currency.
      - Lev, no longer an active currency.
      - Bulgarian Lev.
      - Bahraini Dinar.
      - Burundi Franc.
      - Bermudian Dollar.
      - Brunei Dollar.
      - Boliviano.
      - Peso boliviano, no longer an active currency.
      - Mvdol.
      - Cruzeiro, no longer an active currency.
      - Cruzado, no longer an active currency.
      - Cruzeiro, no longer an active currency.
      - Brazilian Real.
      - New Cruzado, no longer an active currency.
      - Cruzeiro Real, no longer an active currency.
      - Bahamian Dollar.
      - Ngultrum.
      - Kyat, no longer an active currency.
      - Pula.
      - Belarusian Ruble, no longer an active currency.
      - Belarusian Ruble.
      - Belarusian Ruble, no longer an active currency.
      - Belize Dollar.
      - Canadian Dollar.
      - Congolese Franc.
      - WIR Franc, no longer an active currency.
      - WIR Euro.
      - Swiss Franc.
      - WIR Franc.
      - Unidad de Fomento.
      - Chilean Peso.
      - Yuan Renminbi.
      - Colombian Peso.
      - Unidad de Valor Real.
      - Costa Rican Colon.
      - Serbian Dinar, no longer an active currency.
      - Krona A/53, no longer an active currency.
      - Koruna, no longer an active currency.
      - Peso Convertible.
      - Cuban Peso.
      - Cabo Verde Escudo.
      - Cyprus Pound, no longer an active currency.
      - Czech Koruna.
      - Mark der DDR, no longer an active currency.
      - Deutsche Mark, no longer an active currency.
      - Djibouti Franc.
      - Danish Krone.
      - Dominican Peso.
      - Algerian Dinar.
      - Sucre, no longer an active currency.
      - Unidad de Valor Constante (UVC), no longer an active currency.
      - Kroon, no longer an active currency.
      - Egyptian Pound.
      - Nakfa.
      - Spanish Peseta, no longer an active currency.
      - Spanish Peseta, no longer an active currency.
      - Spanish Peseta, no longer an active currency.
      - Ethiopian Birr.
      - Euro.
      - Markka, no longer an active currency.
      - Fiji Dollar.
      - Falkland Islands Pound.
      - French Franc, no longer an active currency.
      - Pound Sterling.
      - Georgian Coupon, no longer an active currency.
      - Lari.
      - Cedi, no longer an active currency.
      - Ghana Cedi, no longer an active currency.
      - Ghana Cedi.
      - Gibraltar Pound.
      - Dalasi.
      - Syli, no longer an active currency.
      - Guinean Franc.
      - Syli, no longer an active currency.
      - Ekwele, no longer an active currency.
      - Drachma, no longer an active currency.
      - Quetzal.
      - Guinea Escudo, no longer an active currency.
      - Guinea-Bissau Peso, no longer an active currency.
      - Guyana Dollar.
      - Hong Kong Dollar.
      - Lempira.
      - Croatian Dinar, no longer an active currency.
      - Kuna.
      - Gourde.
      - Forint.
      - Rupiah.
      - Irish Pound, no longer an active currency.
      - Pound, no longer an active currency.
      - Old Shekel, no longer an active currency.
      - New Israeli Sheqel.
      - Indian Rupee.
      - Iraqi Dinar.
      - Iranian Rial.
      - Old Krona, no longer an active currency.
      - Iceland Krona.
      - Italian Lira, no longer an active currency.
      - Jamaican Dollar.
      - Jordanian Dinar.
      - Yen.
      - Kenyan Shilling.
      - Som.
      - Riel.
      - Comorian Franc.
      - North Korean Won.
      - Won.
      - Kuwaiti Dinar.
      - Cayman Islands Dollar.
      - Tenge.
      - Pathet Lao Kip, no longer an active currency.
      - Lao Kip.
      - Lebanese Pound.
      - Sri Lanka Rupee.
      - Liberian Dollar.
      - Loti.
      - Loti, no longer an active currency.
      - Lithuanian Litas, no longer an active currency.
      - Talonas, no longer an active currency.
      - Luxembourg Convertible Franc, no longer an active currency.
      - Luxembourg Franc, no longer an active currency.
      - Luxembourg Financial Franc, no longer an active currency.
      - Latvian Lats, no longer an active currency.
      - Latvian Ruble, no longer an active currency.
      - Libyan Dinar.
      - Moroccan Dirham.
      - Moldovan Leu.
      - Malagasy Ariary.
      - Malagasy Franc, no longer an active currency.
      - Denar.
      - Mali Franc, no longer an active currency.
      - Kyat.
      - Tugrik.
      - Pataca.
      - Ouguiya, no longer an active currency.
      - Maltese Lira, no longer an active currency.
      - Maltese Pound, no longer an active currency.
      - Mauritius Rupee.
      - Maldive Rupee, no longer an active currency.
      - Rufiyaa.
      - Malawi Kwacha.
      - Mexican Peso.
      - Mexican Peso, no longer an active currency.
      - Mexican Unidad de Inversion (UDI).
      - Malaysian Ringgit.
      - Mozambique Escudo, no longer an active currency.
      - Mozambique Metical, no longer an active currency.
      - Mozambique Metical.
      - Namibia Dollar.
      - Naira.
      - Cordoba, no longer an active currency.
      - Cordoba Oro.
      - Netherlands Guilder, no longer an active currency.
      - Norwegian Krone.
      - Nepalese Rupee.
      - New Zealand Dollar.
      - Rial Omani.
      - Balboa.
      - Sol, no longer an active currency.
      - Inti, no longer an active currency.
      - Sol.
      - Sol, no longer an active currency.
      - Kina.
      - Philippine Peso.
      - Pakistan Rupee.
      - Zloty.
      - Zloty, no longer an active currency.
      - Portuguese Escudo, no longer an active currency.
      - Guarani.
      - Qatari Rial.
      - Rhodesian Dollar, no longer an active currency.
      - Leu A/52, no longer an active currency.
      - Old Leu, no longer an active currency.
      - Romanian Leu.
      - Serbian Dinar.
      - Russian Ruble.
      - Russian Ruble, no longer an active currency.
      - Rwanda Franc.
      - Saudi Riyal.
      - Solomon Islands Dollar.
      - Seychelles Rupee.
      - Sudanese Dinar, no longer an active currency.
      - Sudanese Pound.
      - Sudanese Pound, no longer an active currency.
      - Swedish Krona.
      - Singapore Dollar.
      - Saint Helena Pound.
      - Tolar, no longer an active currency.
      - Slovak Koruna, no longer an active currency.
      - Leone.
      - Somali Shilling.
      - Surinam Dollar.
      - Surinam Guilder, no longer an active currency.
      - South Sudanese Pound.
      - Dobra, no longer an active currency.
      - Rouble, no longer an active currency.
      - El Salvador Colon.
      - Syrian Pound.
      - Lilangeni.
      - Baht.
      - Tajik Ruble, no longer an active currency.
      - Somoni.
      - Turkmenistan Manat, no longer an active currency.
      - Turkmenistan New Manat.
      - Tunisian Dinar.
      - Pa’anga.
      - Timor Escudo, no longer an active currency.
      - Old Turkish Lira, no longer an active currency.
      - Turkish Lira.
      - Trinidad and Tobago Dollar.
      - New Taiwan Dollar.
      - Tanzanian Shilling.
      - Hryvnia.
      - Karbovanet, no longer an active currency.
      - Uganda Shilling, no longer an active currency.
      - Old Shilling, no longer an active currency.
      - Uganda Shilling.
      - US Dollar.
      - US Dollar (Next day).
      - US Dollar (Same day), no longer an active currency.
      - Uruguay Peso en Unidades Indexadas (UI).
      - Old Uruguay Peso, no longer an active currency.
      - Uruguayan Peso, no longer an active currency.
      - Peso Uruguayo.
      - Uzbekistan Sum.
      - Bolivar, no longer an active currency.
      - Bolívar, no longer an active currency.
      - Old Dong, no longer an active currency.
      - Dong.
      - Vatu.
      - Tala.
      - CFA Franc BEAC.
      - Silver.
      - Gold.
      - Bond Markets Unit European Composite Unit (EURCO).
      - Bond Markets Unit European Monetary Unit (E.M.U.-6).
      - Bond Markets Unit European Unit of Account 9 (E.U.A.-9).
      - Bond Markets Unit European Unit of Account 17 (E.U.A.-17).
      - East Caribbean Dollar.
      - SDR (Special Drawing Right).
      - European Currency Unit (E.C.U), no longer an active currency.
      - Gold-Franc, no longer an active currency.
      - UIC-Franc, no longer an active currency.
      - CFA Franc BCEAO.
      - Palladium.
      - CFP Franc.
      - Platinum.
      - RINET Funds Code, no longer an active currency.
      - Sucre.
      - Codes specifically reserved for testing purposes.
      - ADB Unit of Account.
      - The codes assigned for transactions where no currency is involved.
      - Yemeni Dinar, no longer an active currency.
      - Yemeni Rial.
      - New Yugoslavian Dinar, no longer an active currency.
      - New Dinar, no longer an active currency.
      - Yugoslavian Dinar, no longer an active currency.
      - Financial Rand, no longer an active currency.
      - Rand.
      - Zambian Kwacha, no longer an active currency.
      - Zambian Kwacha.
      - New Zaire, no longer an active currency.
      - Zaire, no longer an active currency.
      - Rhodesian Dollar, no longer an active currency.
      - Zimbabwe Dollar, no longer an active currency.
      - Zimbabwe Dollar.
      - Zimbabwe Dollar, no longer an active currency.
      - Zimbabwe Dollar, no longer an active currency.
    description: The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html).
  v1CurrencyCodeIso4217Value:
    type: object
    example:
      value: EUR
    properties:
      value:
        $ref: '#/definitions/v1CurrencyCodeIso4217'
        example: EUR
        description: The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) (if known).
        title: Value
    description: A wrapper for the currency code enum.
    title: CurrencyCodeIso4217Value
  v1DefaultValues:
    type: object
    example:
      value: "2021-09-21T19:00:00.000+00:00"
    properties:
      value:
        type: string
        example: "2021-09-21T19:00:00.000+00:00"
        description: The normalized value of an entity, e.g. for time the ISO8601 date format.
        title: Value
    description: A normalized value of an entity, e.g. for time the ISO8601 date format.
    title: DefaultValues
  v1DurationValues:
    type: object
    example:
      seconds: 0
      unit: days
      value: ""
    properties:
      value:
        type: string
        example: ""
        description: The part of the phrase that expresses a duration.
        title: Value
      unit:
        type: string
        example: days
        description: The unit used to indicate the duration.
        title: Unit
      seconds:
        type: string
        format: uint64
        example: 0
        description: The duration normalized to seconds.
        title: Seconds
    description: A duration and the unit of the duration. Durations are normalized to whole seconds.
    title: DurationValues
  v1Entity:
    type: object
    example:
      ambiguous: false
      endCharIndex: 5
      entityValues:
        - time:
            value: "2021-09-21T19:00:00.000+00:00"
      startCharIndex: 0
      text: Today
      type: TIME
    properties:
      text:
        type: string
        example: Today
        description: The raw text from the phrase where the entity was found.
        title: Text
      type:
        $ref: '#/definitions/v1EntityType'
        example: TIME
        description: The type of entity that was found. This entity type also determines which `values` are returned.
        title: Type
      ambiguous:
        type: boolean
        example: false
        description: Describes if the parsed value has multiple possible values. For example `tomorrow at 7` could either mean `tomorrow 07:00` or `tomorrow 19:00`.
        title: Ambiguous
      startCharIndex:
        type: string
        format: uint64
        example: 0
        description: The starting character index of the entity in the given phrase.
        title: Start Char Index
      endCharIndex:
        type: string
        format: uint64
        example: 5
        description: The ending character index of the entity in the given phrase.
        title: End Char Index
      entityValues:
        type: array
        example:
          - time:
              value: "2021-09-21T19:00:00.000+00:00"
        items:
          $ref: '#/definitions/v1EntityValuesWrapper'
        description: The collection of entity values. If the entity is ambiguous (see `ambiguous`), this collection will contain more than one value. For example `tomorrow at 7` could either mean `tomorrow 07:00` or `tomorrow 19:00`.
        title: Entity Values
    description: A (named) entity. Entities are sub-phrases with structured information, such as person name, locations, time, quantities etc. The process of extracting these entities from natural language is called Named Entity Recognition (NER).
    title: Entity
  v1EntityType:
    type: string
    enum:
      - UNKNOWN
      - AMOUNT_OF_MONEY
      - CREDIT_CARD_NUMBER
      - DISTANCE
      - DURATION
      - EMAIL
      - NUMERAL
      - ORDINAL
      - PHONE_NUMBER
      - PRODUCT_QUANTITY
      - TEMPERATURE
      - TIME
      - URL
      - VOLUME
      - INTERVAL
      - PERSON
      - ORGANISATION
      - PRODUCT
      - PLACE
      - COUNTRY
    default: UNKNOWN
    valueComments:
      - Unknown entity type.
      - Entity type that describes amount of money.
      - 'Entity type that describes credit card number. Supported credit card types are [Visa](https//www.visa.com), [American Express (Amex)](https://www.americanexpress.com), [Discover](https://www.discover.com), [Mastercard](https://www.mastercard.com) and [DinerClub](https://www.dinersclub.com). Note: if a credit card number is [invalid](https://en.wikipedia.org/wiki/Luhn_algorithm), it will not be extracted from the phrase.'
      - Entity type that describes distance. Supports both the metric system (meters, kilometers etc.) and imperial (inch, yard etc.) measurements.
      - Entity type that describes duration. Durations are normalized to whole seconds.
      - Entity type that describes email address.
      - Entity type that describes a numeral. Can be written as digits, words, fractions, floating point numbers, as well as some language-specific ways of expressing certain numbers, such as `"a dozen"`.
      - Entity type that describes an ordinal. Can be written as digits or as words.
      - Entity type that describes a phone number. Note that this phone number is not checked for validity. Supports leading area codes too.
      - Entity type that describes a quantity of a product using a certain unit. Example use-cases are parsing of cooking recipes and grocery lists.
      - Entity type that describes a temperature. Supports values to be expressed as words, digits, fractions and floating point numbers. Units can be degree, Celsius or Fahrenheit.
      - Entity type that describes a time. Supported values are exact times, but also time expressed as words, such as `"tomorrow"` or holidays such as `"GroundHog Day"`.
      - Entity type that describes an URL. Will only be populated if the URL is formatted correctly.
      - Entity type that describes a volume. Supports both metric and imperial measurements.
      - Entity type that describes an interval.
      - Entity type that describes a person, including fictional person names.
      - Entity type that describes an organization, such as companies, agencies, institutions etc.
      - Entity type that describes a product. Vehicles and types of food etc.
      - Entity type that describes a place. Can be cities, countries, states, continents etc., but also descriptions of locations such as "East of the river".
      - Entity type that describes a country.
    description: Type of entity.
  v1EntityValuesWrapper:
    type: object
    example:
      time:
        value: "2021-09-21T19:00:00.000+00:00"
    properties:
      amountOfMoney:
        $ref: '#/definitions/v1AmountOfMoneyValue'
        example:
          cents: 3
          currencyCode:
            value: EUR
          currencyName: Dollar
          units: 3
        description: An amount of money value.
        title: Amount Of Money
      creditCardNumber:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: "5105105105105100"
        description: A credit card number. Supported credit card types are [Visa](https//www.visa.com), [American Express (Amex)](https://www.americanexpress.com), [Discover](https://www.discover.com), [Mastercard](https://www.mastercard.com) and [DinerClub](https://www.dinersclub.com).
        title: Credit Card Number
      distance:
        $ref: '#/definitions/v1UnitValues'
        example:
          unit: meter
        description: A distance value. Supports both the metric system (meters, kilometers etc.) and imperial (inch, yard etc.) measurements.
        title: Distance
      duration:
        $ref: '#/definitions/v1DurationValues'
        example:
          seconds: 0
          unit: days
          value: ""
        description: The duration value. Durations are normalized to whole seconds.
        title: Duration
      emailAddress:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: john@example.com
        description: The email address value. Will not be populated if an email address is invalid (for example due to misspelling).
        title: Email Address
      numeral:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: "5"
        description: The numeral value. Can be written as digits, words, fractions, floating point numbers, as well as some language-specific ways of expressing certain numbers, such as `"a dozen"`.
        title: Numeral
      ordinal:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: first
        description: The ordinal value. Can be written as digits or as words.
        title: Ordinal
      phoneNumber:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: "0612345678"
        description: The phone number value. Note that this phone number is not checked for validity. Supports leading area codes too.
        title: Phone Number
      productQuantity:
        $ref: '#/definitions/v1ProductQuantityValue'
        example:
          product: milk
          unit: mg
          value: "3"
        description: The quantity of a product using a certain unit. Example use-cases are parsing of cooking recipes and grocery lists.
        title: Product Quantity
      temperature:
        $ref: '#/definitions/v1UnitValues'
        example:
          unit: celsius
        description: The temperature value. Supports values to be expressed as words, digits, fractions and floating point numbers. Units can be degree, Celsius or Fahrenheit.
        title: Temperature
      time:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: "2021-09-21T19:00:00.000+00:00"
        description: The time value. Supported values are exact times, but also time expressed as words, such as `"tomorrow"` or holidays such as `"GroundHog Day"`.
        title: Time
      url:
        $ref: '#/definitions/v1UrlValues'
        example:
          domain: messagebird.com
          value: https://messagebird.com/en/solutions/faq-bots
        description: The URL value. Will only be populated if the URL is formatted correctly.
        title: Url
      volume:
        $ref: '#/definitions/v1UnitValues'
        example:
          unit: gallons
        description: The volume value. Supports both metric and imperial measurements.
        title: Volume
      interval:
        $ref: '#/definitions/v1IntervalValues'
        example:
          end: "2021-09-21T21:00:00.000+00:00"
          start: "2021-09-21T19:00:00.000+00:00"
        description: The interval value. Intervals are given by a start and an end time.
        title: Interval
      person:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: Robert Vis
        description: The person name, including fictional person names.
        title: Person
      organization:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: MessageBird
        description: The organization name.
        title: Organization
      product:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: iPhone
        description: The product value. Includes vehicles, devices, types of food etc.
        title: Product
      place:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: East of the river
        description: The place value.
        title: Place
      country:
        $ref: '#/definitions/v1DefaultValues'
        example:
          value: Germany
        description: The country value.
        title: Country
    description: A wrapper for entity values with varying type and structure.
    title: EntityValuesWrapper
  v1IntervalValues:
    type: object
    example:
      end: "2021-09-21T21:00:00.000+00:00"
      start: "2021-09-21T19:00:00.000+00:00"
    properties:
      start:
        type: string
        example: "2021-09-21T19:00:00.000+00:00"
        description: The normalized start date in ISO8601 date format.
        title: Start
      end:
        type: string
        example: "2021-09-21T21:00:00.000+00:00"
        description: The normalized end date in ISO8601 date format.
        title: End
    description: A start time and an end time of an interval.
    title: IntervalValues
  v1Language:
    type: object
    example:
      iso6393Code: nld
      languageCode: NLD
      name: Dutch
    properties:
      iso6393Code:
        type: string
        example: nld
        description: The ISO-639-3 code of the language.
        title: Iso 639 3 Code
      name:
        type: string
        example: Dutch
        description: The English name of the language.
        title: Name
      languageCode:
        $ref: '#/definitions/v1LanguageCode'
        example: NLD
        description: The enum value of the ISO639-3 language code.
        title: Language Code
    description: Language that was detected from the given phrase.
    title: Language
  v1LanguageCode:
    type: string
    enum:
      - LANGUAGE_INVALID
      - LANGUAGE_UNDETERMINED
      - ENG
      - RUS
      - DEU
      - FRA
      - ITA
      - JPN
      - SPA
      - CEB
      - TUR
      - POR
      - UKR
      - EPO
      - POL
      - SWE
      - NLD
      - HEB
      - ZHO
      - HUN
      - ARA
      - CAT
      - FIN
      - CES
      - FAS
      - SRP
      - ELL
      - VIE
      - BUL
      - KOR
      - NOR
      - MKD
      - RON
      - IND
      - THA
      - HYE
      - DAN
      - TAM
      - HIN
      - HRV
      - HBS
      - BEL
      - KAT
      - TEL
      - KAZ
      - WAR
      - LIT
      - GLG
      - SLK
      - BEN
      - EUS
      - SLV
      - KAN
      - MAL
      - MAR
      - EST
      - AZE
      - MSA
      - SQI
      - LAT
      - BOS
      - NNO
      - URD
      - LAV
      - MYA
      - TAT
      - AFR
      - OCI
      - NDS
      - KIR
      - AST
      - TGL
      - ISL
      - INA
      - SIN
      - GUJ
      - KHM
      - BRE
      - BAK
      - UZB
      - BOD
      - PAN
      - VOL
      - ALS
      - NEP
      - CYM
      - JBO
      - FRY
      - MON
      - LTZ
      - CHE
      - UIG
      - TGK
      - SCO
      - SAN
      - CHV
      - JAV
      - MIN
      - IDO
      - ORI
      - ASM
      - NEW
      - GLE
      - MLG
      - ARG
      - CKB
      - SWA
      - BAR
      - LMO
      - YID
      - ARZ
      - MHR
      - AZB
      - SAH
      - PNB
      - SUN
      - BPY
      - PMS
      - ILO
      - WUU
      - KUR
      - PUS
      - ILE
      - XMF
      - YUE
      - GOM
      - LIM
      - MWL
      - COR
      - SND
      - HSB
      - SCN
      - GLA
      - PAM
      - BHO
      - MAI
      - VEC
      - MLT
      - DIV
      - WLN
      - MZN
      - AMH
      - QUE
      - CBK
      - TUK
      - ROH
      - OSS
      - VLS
      - YOR
      - LAO
      - LEZ
      - SOM
      - MYV
      - DIQ
      - MRJ
      - DSB
      - FRR
      - HAT
      - GRN
      - BXR
      - KOM
      - SRD
      - KRC
      - BCL
      - NAP
      - GLV
      - AVA
      - RUE
      - XAL
      - PFL
      - DTY
      - HIF
      - COS
      - LRC
      - VEP
      - TYV
      - NOB
      - SNA
      - KIN
      - IBO
      - SMO
      - SOT
      - MRI
      - WOL
      - XHO
      - HAU
      - HAW
      - NYA
      - ZUL
      - HMN
    default: LANGUAGE_INVALID
    valueComments:
      - Language code is invalid.
      - Language could not be determined.
      - English.
      - Russian.
      - German.
      - French.
      - Italian.
      - Japanese.
      - Spanish.
      - Cebuano.
      - Turkish.
      - Portuguese.
      - Ukrainian.
      - Esperanto.
      - Polish.
      - Swedish.
      - Dutch.
      - Hebrew.
      - Chinese.
      - Hungarian.
      - Arabic.
      - Catalan.
      - Finnish.
      - Czech.
      - Persian.
      - Serbian.
      - Greek.
      - Vietnamese.
      - Bulgarian.
      - Korean.
      - Norwegian.
      - Macedonian.
      - Romanian.
      - Indonesian.
      - Thai.
      - Armenian.
      - Danish.
      - Tamil.
      - Hindi.
      - Croatian.
      - Serbo-Croatian.
      - Belarusian.
      - Georgian.
      - Telugu.
      - Kazakh.
      - Waray.
      - Lithuanian.
      - Galician.
      - Slovak.
      - Bengali.
      - Basque.
      - Slovenian.
      - Kannada.
      - Malayalam.
      - Marathi.
      - Estonian.
      - Azerbaijani.
      - Malay.
      - Albanian.
      - Latin.
      - Bosnian.
      - Norwegian Nynorsk.
      - Urdu.
      - Latvian.
      - Burmese.
      - Tatar.
      - Afrikaans.
      - Occitan.
      - Low German.
      - Kirghiz.
      - Asturian.
      - Tagalog.
      - Icelandic.
      - Interlingua.
      - Sinhala.
      - Gujarati.
      - Central Khmer.
      - Breton.
      - Bashkir.
      - Uzbek.
      - Tibetan.
      - Panjabi.
      - Volapük.
      - Tosk Albanian.
      - Nepali.
      - Welsh.
      - Lojban.
      - Western Frisian.
      - Mongolian.
      - Luxembourgish.
      - Chechen.
      - Uighur.
      - Tajik.
      - Scots.
      - Sanskrit.
      - Chuvash.
      - Javanese.
      - Minangkabau.
      - Ido.
      - Oriya.
      - Assamese.
      - Newari.
      - Irish.
      - Malagasy.
      - Aragonese.
      - Central Kurdish.
      - Swahili.
      - Bavarian.
      - Lombard.
      - Yiddish.
      - Egyptian Arabic.
      - Eastern Mari.
      - South Azerbaijani.
      - Yakut.
      - Western Panjabi.
      - Sundanese.
      - Bishnupriya.
      - Piemontese.
      - Iloko.
      - Wu Chinese.
      - Kurdish.
      - Pushto.
      - Interlingue.
      - Mingrelian.
      - Yue Chinese.
      - Goan Konkani.
      - Limburgan.
      - Mirandese.
      - Cornish.
      - Sindhi.
      - Upper Sorbian.
      - Sicilian.
      - Scottish Gaelic.
      - Pampanga.
      - Bhojpuri.
      - Maithili.
      - Venetian.
      - Maltese.
      - Dhivehi.
      - Walloon.
      - Mazanderani.
      - Amharic.
      - Quechua.
      - Chavacano.
      - Turkmen.
      - Romansh.
      - Ossetian.
      - Vlaams.
      - Yoruba.
      - Lao.
      - Lezghian.
      - Somali.
      - Erzya.
      - Dimli.
      - Western Mari.
      - Lower Sorbian.
      - Northern Frisian.
      - Haitian.
      - Guarani.
      - Russia Buriat.
      - Komi.
      - Sardinian.
      - Karachay-Balkar.
      - Central Bikol.
      - Neapolitan.
      - Manx.
      - Avaric.
      - Rusyn.
      - Kalmyk.
      - Pfaelzisch.
      - Dotyali.
      - Fiji Hindi.
      - Corsican.
      - Northern Luri.
      - Veps.
      - Tuvinian.
      - Norwegian Bokmål.
      - Shona.
      - Kinyarwanda.
      - Igbo.
      - Samoan.
      - Southern Sotho.
      - Maori.
      - Wolof.
      - Xhosa.
      - Hausa.
      - Hawaiian.
      - Nyanja.
      - Zulu.
      - Hmong.
    description: 'Language code in ISO639-3 format. More info can be found here: https://iso639-3.sil.org/code_tables/639/data.'
  v1ListSupportedLanguagesResponses:
    type: object
    example:
      entitiesPerLanguage:
        - entityTypes:
            - GEOPOLITICAL
            - URL
            - TIME
            - NUMERAL
          language:
            iso6393Code: nld
            languageCode: NLD
            name: Dutch
        - entityTypes:
            - GEOPOLITICAL
            - URL
            - TIME
            - NUMERAL
          language:
            iso6393Code: eng
            languageCode: ENG
            name: English
        - entityTypes:
            - GEOPOLITICAL
            - URL
            - TIME
            - NUMERAL
          language:
            iso6393Code: spa
            languageCode: SPA
            name: Spanish
        - entityTypes:
            - GEOPOLITICAL
            - URL
            - TIME
            - NUMERAL
          language:
            iso6393Code: zho
            languageCode: ZHO
            name: Chinese
      languages:
        - iso6393Code: nld
          languageCode: NLD
          name: Dutch
        - iso6393Code: eng
          languageCode: ENG
          name: English
        - iso6393Code: spa
          languageCode: SPA
          name: Spanish
        - iso6393Code: zho
          languageCode: ZHO
          name: Chinese
    properties:
      languages:
        type: array
        example:
          - iso6393Code: nld
            languageCode: NLD
            name: Dutch
          - iso6393Code: eng
            languageCode: ENG
            name: English
          - iso6393Code: spa
            languageCode: SPA
            name: Spanish
          - iso6393Code: zho
            languageCode: ZHO
            name: Chinese
        items:
          $ref: '#/definitions/v1Language'
        description: Collection of supported languages.
        title: Languages
      entitiesPerLanguage:
        type: array
        example:
          - entityTypes:
              - GEOPOLITICAL
              - URL
              - TIME
              - NUMERAL
            language:
              iso6393Code: nld
              languageCode: NLD
              name: Dutch
          - entityTypes:
              - GEOPOLITICAL
              - URL
              - TIME
              - NUMERAL
            language:
              iso6393Code: eng
              languageCode: ENG
              name: English
          - entityTypes:
              - GEOPOLITICAL
              - URL
              - TIME
              - NUMERAL
            language:
              iso6393Code: spa
              languageCode: SPA
              name: Spanish
          - entityTypes:
              - GEOPOLITICAL
              - URL
              - TIME
              - NUMERAL
            language:
              iso6393Code: zho
              languageCode: ZHO
              name: Chinese
        items:
          $ref: '#/definitions/v1SupportedEntitiesForLanguage'
        description: Collection of supported entity types per language.
        title: Entities Per Language
    description: A response with a collection of languages and the entity types supported by those languages.
    title: ListSupportedLanguagesResponses
  v1PredictEntitiesRequest:
    type: object
    example:
      entityTypes:
        - GEOPOLITICAL
        - URL
        - TIME
        - NUMERAL
      language: ENG
      phrase: Today we're in Amsterdam, building two chatbots using https://messagebird.com/en/solutions/faq-bots
      timezone: Europe/Amsterdam
    properties:
      phrase:
        type: string
        example: Today we're in Amsterdam, building two chatbots using https://messagebird.com/en/solutions/faq-bots
        description: The phrase to extract named entities from.
        title: Phrase
      language:
        $ref: '#/definitions/v1LanguageCode'
        example: ENG
        description: The language of the given phrase. If you're unsure of the language of a phrase, use our Language Detection API.
        title: Language
      entityTypes:
        type: array
        example:
          - GEOPOLITICAL
          - URL
          - TIME
          - NUMERAL
        items:
          $ref: '#/definitions/v1EntityType'
        description: A collection of entity types that can be detected. If empty, all found types are returned.
        title: Entity Types
      timezone:
        type: string
        example: Europe/Amsterdam
        description: The name of the timezone the samples should be detected in. For time or date related entities this ensures that the values are converted to the correct timezone. For an overview of available timezones see [this list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
        title: Timezone
    description: "A request for predicting the entities from a given phrase. This process is also referred to as named entity recognition. It is possible to pre-specify the language when calling this endpoint. Otherwise, the Named Entity Recognition API will attempt to infer the language and proceed with extraction of the entities. \n\nIf no entities could be found, it will return an empty collection."
    title: PredictEntitiesRequest
  v1PredictEntitiesResponse:
    type: object
    example:
      entities:
        - ambiguous: false
          endCharIndex: 5
          entityValues:
            - time:
                value: "2021-09-21T19:00:00.000+00:00"
          startCharIndex: 0
          text: Today
          type: TIME
        - ambiguous: false
          endCharIndex: 24
          entityValues:
            - {}
          startCharIndex: 15
          text: Amsterdam
          type: GEOPOLITICAL
        - ambiguous: false
          endCharIndex: 38
          entityValues:
            - numeral:
                value: "5"
          startCharIndex: 35
          text: two
          type: NUMERAL
        - ambiguous: false
          endCharIndex: 99
          entityValues:
            - url:
                domain: messagebird.com
                value: https://messagebird.com/en/solutions/faq-bots
          startCharIndex: 54
          text: https://messagebird.com/en/solutions/faq-bots
          type: URL
    properties:
      entities:
        type: array
        example:
          - ambiguous: false
            endCharIndex: 5
            entityValues:
              - time:
                  value: "2021-09-21T19:00:00.000+00:00"
            startCharIndex: 0
            text: Today
            type: TIME
          - ambiguous: false
            endCharIndex: 24
            entityValues:
              - {}
            startCharIndex: 15
            text: Amsterdam
            type: GEOPOLITICAL
          - ambiguous: false
            endCharIndex: 38
            entityValues:
              - numeral:
                  value: "5"
            startCharIndex: 35
            text: two
            type: NUMERAL
          - ambiguous: false
            endCharIndex: 99
            entityValues:
              - url:
                  domain: messagebird.com
                  value: https://messagebird.com/en/solutions/faq-bots
            startCharIndex: 54
            text: https://messagebird.com/en/solutions/faq-bots
            type: URL
        items:
          $ref: '#/definitions/v1Entity'
        description: The collection of entities that were extracted from the given phrase. The collection is empty if no entities could be found.
        title: Entities
    description: Response payload that is returned when predicting entities. Contains an empty list when no entities could be found.
    title: PredictEntitiesResponse
  v1ProductQuantityValue:
    type: object
    example:
      product: milk
      unit: mg
      value: "3"
    properties:
      value:
        type: string
        example: "3"
        description: The amount of the unit.
        title: Value
      unit:
        type: string
        example: mg
        description: The unit describing the amount.
        title: Unit
      product:
        type: string
        example: milk
        description: The extracted product.
        title: Product
    description: A quantity of a product using a certain unit. Example use-cases are parsing of cooking recipes and shopping.
    title: ProductQuantityValue
  v1SupportedEntitiesForLanguage:
    type: object
    example:
      entityTypes:
        - GEOPOLITICAL
        - URL
        - TIME
        - NUMERAL
      language:
        iso6393Code: nld
        languageCode: NLD
        name: Dutch
    properties:
      language:
        $ref: '#/definitions/v1Language'
        title: Language
      entityTypes:
        type: array
        example:
          - GEOPOLITICAL
          - URL
          - TIME
          - NUMERAL
        items:
          $ref: '#/definitions/v1EntityType'
        description: Collection of the supported entity types for this language.
        title: Entity Types
    description: A language and the entity types supported by that language.
    title: SupportedEntitiesForLanguage
  v1UnitValues:
    type: object
    example:
      unit: liter
    properties:
      unit:
        type: string
        example: liter
        description: The unit describing the amount.
        title: Unit
    description: An amount and a unit of the amount.
    title: UnitValues
  v1UrlValues:
    type: object
    example:
      domain: messagebird.com
      value: https://messagebird.com/en/solutions/faq-bots
    properties:
      value:
        type: string
        example: https://messagebird.com/en/solutions/faq-bots
        description: The extracted url.
        title: Value
      domain:
        type: string
        example: messagebird.com
        description: The domain of the url.
        title: Domain
    description: A URL and its domain.
    title: UrlValues
securityDefinitions:
  AccessKey:
    type: apiKey
    name: Authorization
    in: header
externalDocs:
  description: Find our official documentation in the MessageBird Docs
  url: https://developers.messagebird.com/api
